version: '3.8'

services:
  nodeapp:
    build: 
      context: .
      dockerfile: /home/selfmade/Desktop/wickrDuo/chat/Dockerfile.nodeapp
    container_name: nodeapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - web

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom nginx config
      - ./nginx/ssl:/etc/nginx/ssl  # Mount SSL certificates
    depends_on:
      - nodeapp
    networks:
      - web

networks:
  web:
    driver: bridge
